### ISSUE TITLE
Error While Running a Fresh Clone

### ISSUE THREAD

**Issue by juicebyjustin** [steffbeckers/code-generator#4]
I am trying to run this project from a fresh clone, and I get an error message running `dotnet watch run` or `docker-compose -up`. There are no log messages after the message below.

How to replicate:
1. Clone repo.
2. Open root directory in terminal.
2. Run `dotnet build`
3. CD to `CodeGen`
3. Run `dotnet watch run`

Complete Log Output: [https://gist.github.com/juicebyjustin/d5d61c7b50550d19ab65ffd06cb12875](https://gist.github.com/juicebyjustin/d5d61c7b50550d19ab65ffd06cb12875)

Error Message:
```
fail: CodeGen.Worker[0]
      No such file or directory
      System.ComponentModel.Win32Exception (2): No such file or directory
         at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start()
         at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
         at CodeGen.Runners.DotNETProjectRunner.Run() in /Users/justin/Documents/GitHub/code-generator/CodeGen/Runners/DotNETProjectRunner.cs:line 50
         at CodeGen.Worker.ExecuteAsync(CancellationToken cancellationToken) in /Users/justin/Documents/GitHub/code-generator/CodeGen/Worker.cs:line 47
```

[CodeGen/Runners/DotNETProjectRunner.cs:line 50:](https://github.com/steffbeckers/code-generator/blob/b9617ada8ffc0c08cbab2725a0b342d041eb42cb/CodeGen/Runners/DotNETProjectRunner.cs#L50)
```
await Process.Start(openSwagger).WaitForExitAsync();
```

**Comment by steffbeckers** [comment]
The error you get might be related to a cross-platform issue, since you get a Win32Exception. Currently I'm using windows explorer to open a browser and navigate to the running API's swagger page.

```
// Open swagger
_logger.LogInformation("Opening Swagger docs: " + _outputProjectPath);

ProcessStartInfo openSwagger = new ProcessStartInfo("explorer");
openSwagger.Arguments = _projectTemplateSettings.DotNET.StartupProjectURL;
await Process.Start(openSwagger).WaitForExitAsync();
```

I think this functionality needs to be changed or removed.

**Comment by juicebyjustin** [comment]
I switched from VS Code to Visual Studio and actually debugged the project. I see that it's trying to start the web browser at `https://localhost:44370`. I'm running on a Mac so of course `explorer` is not available. However, Swagger is not running on port 44370.

**Comment by steffbeckers** [comment]
Can you try to run the generated project from in the _Output folder?
